---
config:
  theme: redux
---
flowchart LR
  subgraph Ingestion["Ingestion"]
      A["Batch File</br>or Stream"]
  end
  subgraph Processing["Processing"]
      B["Stream Processor"]
  end
  subgraph Indexing["Indexing"]
      C["Search Index"]
  end
  subgraph Search["Search"]
      D["Search API"]
  end
  subgraph Pricing["Pricing"]
      E["Pricing Cache"]
  end

  A --> B
  B --> C
  D --> C
  D --> E
